#
# This source file is part of the Stanford Spezi open-source project
#
# SPDX-FileCopyrightText: 2025 Stanford University and the project authors (see CONTRIBUTORS.md)
#
# SPDX-License-Identifier: MIT
# 

exclude:
  - "Sources/SpeziHealthKit/Sample Types/SampleType+QuantityTypes.swift"
  - "Sources/SpeziHealthKit/Sample Types/SampleType+CategoryTypes.swift"
  - "Sources/SpeziHealthKit/Sample Types/SampleType+CorrelationTypes.swift"
