exclude:
  - "Sources/SpeziHealthKit/SampleTypes/SampleType+QuantityTypes.swift"
  - "Sources/SpeziHealthKit/SampleTypes/SampleType+CategoryTypes.swift"
  - "Sources/SpeziHealthKit/SampleTypes/SampleType+CorrelationTypes.swift"
